'use client';
import Image from 'next/image';
import {useMemo,useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {ShoppingBag,X,Plus,Minus,Trash2,Clock,MapPin,Phone,ChevronRight,CheckCircle2,Globe} from 'lucide-react';
import {foods,categories,pickupTimes,Food,Lang} from '@/lib/data';
import th from '@/public/locales/th.json'; import en from '@/public/locales/en.json';

type CartItem={food:Food;qty:number;addons:string[]};
export default function Home(){
 const [lang,setLang]=useState<Lang>('th'); const t=lang==='th'?th:en;
 const [cat,setCat]=useState('all'); const [selected,setSelected]=useState<Food|null>(null); const [cart,setCart]=useState<CartItem[]>([]); const [cartOpen,setCartOpen]=useState(false); const [checkout,setCheckout]=useState(false); const [success,setSuccess]=useState(false); const [pickup,setPickup]=useState('12:00'); const [addons,setAddons]=useState<string[]>([]);
 const [form,setForm]=useState({name:'',phone:'',note:''});
 const filtered=useMemo(()=>cat==='all'?foods:foods.filter(f=>f.category===cat),[cat]);
 const total=cart.reduce((s,i)=>s+i.food.price*i.qty+i.addons.length*15*i.qty,0);
 const count=cart.reduce((s,i)=>s+i.qty,0);
 const add=(food:Food, selectedAddons:string[]=[])=>{setCart(c=>{const idx=c.findIndex(i=>i.food.id===food.id&&JSON.stringify(i.addons)===JSON.stringify(selectedAddons)); if(idx>=0){const n=[...c];n[idx]={...n[idx],qty:n[idx].qty+1};return n} return [...c,{food,qty:1,addons:selectedAddons}]});setSelected(null);setAddons([]);setCartOpen(true)};
 const change=(idx:number,d:number)=>setCart(c=>c.map((x,i)=>i===idx?{...x,qty:Math.max(0,x.qty+d)}:x).filter(x=>x.qty>0));
 const orderNo='BP-'+Math.floor(100000+Math.random()*899999);
 const submit=()=>{if(!form.name||!form.phone)return;setCheckout(false);setCartOpen(false);setSuccess(true)};
 return <div className="min-h-screen bg-[#fffdf9]">
  <nav className="sticky top-0 z-40 border-b border-orange-100/70 glass"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-8">
   <a href="#home" className="flex items-center gap-2 font-black tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f4512a] text-white">B</span><span>{t.brand}</span></a>
   <div className="hidden items-center gap-7 text-sm font-medium md:flex"><a href="#menu">{t.menu}</a><a href="#about">{t.about}</a><a href="#contact">{t.contact}</a></div>
   <div className="flex items-center gap-2"><button onClick={()=>setLang(lang==='th'?'en':'th')} className="flex items-center gap-1 rounded-full border border-gray-200 bg-white px-3 py-2 text-xs font-bold"><Globe size={14}/>{lang.toUpperCase()} <span className="text-gray-300">|</span>{lang==='th'?'EN':'TH'}</button><button onClick={()=>setCartOpen(true)} className="relative grid h-10 w-10 place-items-center rounded-full bg-gray-900 text-white"><ShoppingBag size={18}/>{count>0&&<span className="absolute -right-1 -top-1 grid h-5 w-5 place-items-center rounded-full bg-[#f4512a] text-[10px]">{count}</span>}</button></div>
  </div></nav>
  <main id="home">
   <section className="mx-auto grid max-w-7xl gap-8 px-4 pb-14 pt-7 md:grid-cols-2 md:items-center md:px-8 md:pt-14"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1.5 text-xs font-bold text-[#d9401e]">● {t.ready}</div><h1 className="max-w-xl text-4xl font-black leading-tight tracking-tight md:text-6xl">{t.heroTitle}</h1><p className="mt-5 max-w-lg text-base leading-7 text-gray-500 md:text-lg">{t.heroSub}</p><div className="mt-7 flex flex-wrap gap-3"><a href="#menu" className="rounded-2xl bg-[#f4512a] px-6 py-3.5 font-bold text-white shadow-lg shadow-orange-200 transition hover:-translate-y-0.5">{t.orderNow} <ChevronRight className="ml-1 inline" size={18}/></a><div className="flex items-center gap-2 rounded-2xl border border-gray-200 bg-white px-4 py-3"><Clock size={18} className="text-[#f4512a]"/><span className="text-sm"><b>{t.pickup}</b><br/><span className="text-gray-500">{pickup}</span></span></div></div></div><div className="relative overflow-hidden rounded-[2rem] soft"><Image src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=90" alt="Food" width={1200} height={900} className="h-[360px] w-full object-cover md:h-[500px]" priority/><div className="absolute bottom-4 left-4 rounded-2xl glass px-4 py-3 text-sm shadow-lg"><b>⚡ Fast pickup</b><br/><span className="text-gray-500">10–20 min</span></div></div></section>
   <section id="menu" className="mx-auto max-w-7xl px-4 py-8 md:px-8"><div className="mb-6 flex items-end justify-between"><div><p className="text-sm font-bold text-[#f4512a]">MENU</p><h2 className="text-3xl font-black">{t.menu}</h2></div><span className="text-sm text-gray-400">{filtered.length} items</span></div><div className="hide-scrollbar mb-8 flex gap-2 overflow-x-auto pb-1">{categories.map(([id,thName,enName])=><button key={id} onClick={()=>setCat(id)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-bold transition ${cat===id?'bg-gray-900 text-white':'bg-white text-gray-600 ring-1 ring-gray-200 hover:bg-orange-50'}`}>{lang==='th'?thName:enName}</button>)}</div><motion.div layout className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{filtered.map(f=><motion.article layout key={f.id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="group overflow-hidden rounded-3xl bg-white soft transition hover:-translate-y-1"><button onClick={()=>setSelected(f)} className="w-full text-left"><div className="relative overflow-hidden"><Image src={f.image} alt={f.name[lang]} width={900} height={650} className="h-52 w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute right-3 top-3 rounded-full bg-white/90 px-3 py-1 text-xs font-black">฿{f.price}</span></div><div className="p-4"><h3 className="font-extrabold">{f.name[lang]}</h3><p className="mt-1 line-clamp-2 text-sm leading-6 text-gray-500">{f.desc[lang]}</p></div></button><div className="px-4 pb-4"><button onClick={()=>add(f)} className="w-full rounded-xl bg-orange-50 py-3 text-sm font-bold text-[#df421f] transition hover:bg-[#f4512a] hover:text-white">{t.add}</button></div></motion.article>)}</motion.div></section>
   <section id="about" className="mx-auto max-w-7xl px-4 py-16 md:px-8"><div className="rounded-[2rem] bg-[#fff1df] p-7 md:p-12"><div className="max-w-2xl"><p className="font-bold text-[#f4512a]">BITE & PICK</p><h2 className="mt-2 text-3xl font-black">{t.heroSub}</h2><p className="mt-4 leading-7 text-gray-600">{lang==='th'?'สั่งล่วงหน้า ลดเวลารอหน้าร้าน และเลือกรับอาหารในช่วงเวลาที่สะดวก':'Order ahead, skip the wait, and pick up when it suits you.'}</p></div></div></section>
  </main>
  <footer id="contact" className="border-t border-gray-100 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 md:grid-cols-3 md:px-8"><div><b className="text-lg">{t.brand}</b><p className="mt-3 text-sm leading-6 text-gray-500">{t.address}</p></div><div className="text-sm text-gray-600"><p className="flex gap-2"><Clock size={17}/>{t.hours}</p><p className="mt-3 flex gap-2"><Phone size={17}/>{t.call}</p></div><a href="https://maps.google.com" target="_blank" className="flex items-start gap-2 text-sm font-bold text-[#f4512a]"><MapPin size={18}/>{t.map}</a></div></footer>
  <AnimatePresence>{selected&&<div className="fixed inset-0 z-50 grid place-items-end bg-black/40 p-0 md:place-items-center md:p-5" onClick={()=>setSelected(null)}><motion.div initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} exit={{y:40,opacity:0}} onClick={e=>e.stopPropagation()} className="max-h-[92vh] w-full overflow-y-auto rounded-t-[2rem] bg-white md:max-w-xl md:rounded-[2rem]"><div className="relative"><Image src={selected.image} alt="" width={900} height={600} className="h-64 w-full object-cover"/><button onClick={()=>setSelected(null)} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white"><X size={18}/></button></div><div className="p-6"><h2 className="text-2xl font-black">{selected.name[lang]}</h2><p className="mt-2 text-gray-500">{selected.desc[lang]}</p><p className="mt-4 text-xl font-black">฿{selected.price}</p><div className="mt-6"><h3 className="font-bold">{t.options}</h3><div className="mt-3 grid gap-2 sm:grid-cols-3">{[['egg',t.egg],['cheese',t.cheese],['bacon',t.bacon]].map(([id,label])=><button key={id} onClick={()=>setAddons(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id])} className={`rounded-xl border p-3 text-sm font-semibold ${addons.includes(id)?'border-[#f4512a] bg-orange-50 text-[#d9401e]':'border-gray-200'}`}>+ ฿15<br/>{label}</button>)}</div></div><button onClick={()=>add(selected,addons)} className="mt-7 w-full rounded-2xl bg-[#f4512a] py-4 font-bold text-white">{t.add} · ฿{selected.price+addons.length*15}</button></div></motion.div></div>}
  {cartOpen&&<div className="fixed inset-0 z-50 bg-black/30" onClick={()=>setCartOpen(false)}><motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} onClick={e=>e.stopPropagation()} className="ml-auto flex h-full w-full max-w-md flex-col bg-white"><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-black">{t.cart}</h2><button onClick={()=>setCartOpen(false)}><X/></button></div><div className="flex-1 overflow-y-auto p-5">{cart.length===0?<div className="grid h-full place-items-center text-center text-gray-400"><ShoppingBag size={42}/><p>{t.empty}</p></div>:cart.map((i,idx)=><div key={idx} className="mb-4 flex gap-3 rounded-2xl bg-gray-50 p-3"><Image src={i.food.image} alt="" width={80} height={80} className="h-20 w-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><b className="block truncate">{i.food.name[lang]}</b><p className="mt-1 text-sm text-gray-500">฿{i.food.price+i.addons.length*15} × {i.qty}</p><div className="mt-2 flex items-center gap-2"><button onClick={()=>change(idx,-1)} className="grid h-7 w-7 place-items-center rounded-lg bg-white"><Minus size={14}/></button><span className="text-sm font-bold">{i.qty}</span><button onClick={()=>change(idx,1)} className="grid h-7 w-7 place-items-center rounded-lg bg-white"><Plus size={14}/></button></div></div><button onClick={()=>setCart(c=>c.filter((_,x)=>x!==idx))} className="self-start text-gray-400"><Trash2 size={16}/></button></div>)}</div>{cart.length>0&&<div className="border-t p-5"><div className="mb-4 flex justify-between text-lg font-black"><span>{t.total}</span><span>฿{total}</span></div><button onClick={()=>setCheckout(true)} className="w-full rounded-2xl bg-gray-900 py-4 font-bold text-white">{t.confirmCart}</button></div>}</motion.aside></div>}
  {checkout&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/40 p-4"><motion.div initial={{scale:.96,opacity:0}} animate={{scale:1,opacity:1}} className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-[2rem] bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{t.checkout}</h2><button onClick={()=>setCheckout(false)}><X/></button></div><label className="mt-6 block text-sm font-bold">{t.pickup}</label><div className="mt-2 grid grid-cols-3 gap-2">{pickupTimes.map(x=><button key={x} onClick={()=>setPickup(x)} className={`rounded-xl border p-3 text-sm font-bold ${pickup===x?'border-[#f4512a] bg-orange-50 text-[#d9401e]':''}`}>{x}</button>)}</div><div className="mt-6 space-y-3"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={t.name} className="w-full rounded-xl border border-gray-200 p-3 outline-none focus:border-[#f4512a]"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder={t.phone} className="w-full rounded-xl border border-gray-200 p-3 outline-none focus:border-[#f4512a]"/><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder={t.note} rows={3} className="w-full rounded-xl border border-gray-200 p-3 outline-none focus:border-[#f4512a]"/></div><div className="my-5 rounded-2xl bg-gray-50 p-4"><div className="flex justify-between"><span>{t.total}</span><b>฿{total}</b></div><div className="mt-2 flex justify-between text-sm text-gray-500"><span>{t.pickup}</span><b>{pickup}</b></div></div><button onClick={submit} className="w-full rounded-2xl bg-[#f4512a] py-4 font-bold text-white">{t.placeOrder}</button></motion.div></div>}
  {success&&<div className="fixed inset-0 z-[70] grid place-items-center bg-[#fffdf9] p-5"><div className="w-full max-w-md text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-green-50 text-green-600"><CheckCircle2 size={44}/></div><h1 className="mt-6 text-3xl font-black">{t.success}</h1><p className="mt-2 text-gray-500">{t.pleasePickup}</p><div className="mt-6 rounded-3xl bg-white p-6 soft"><p className="text-sm text-gray-400">{t.orderNumber}</p><p className="mt-1 text-3xl font-black tracking-wider">{orderNo}</p><div className="mt-5 flex justify-between border-t pt-4 text-sm"><span>{t.pickup}</span><b>{pickup}</b></div><div className="mt-2 flex justify-between text-sm"><span>{t.total}</span><b>฿{total}</b></div></div><button onClick={()=>{setSuccess(false);setCart([])}} className="mt-6 rounded-2xl bg-gray-900 px-7 py-3.5 font-bold text-white">{lang==='th'?'กลับไปหน้าเมนู':'Back to Menu'}</button></div></div>}
  </AnimatePresence>
 </div>
}
